
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost/TempDatabase
    username: root
    password: new-password
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect







server.port: 8090
